#config_version=6

ball_devices:
  bd_trough:
    ball_switches: s_trough
    eject_coil: c_trough_eject
    eject_targets: playfield
    tags: trough, home, drain
    
  bd_saucer:
    ball_switches: s_saucer
    eject_coil: c_saucer
    eject_targets: playfield
    eject_timeouts: 2s
    mechanical_eject: false
    tags: saucer, eject
    ball_search_order: 20

# -------------------------------
# DROP TARGETS
# -------------------------------
drop_targets:
  s_right_bank_target_left:
    switch: s_right_bank_target_left
  s_right_bank_target_middle:
    switch: s_right_bank_target_middle
  s_right_bank_target_right:
    switch: s_right_bank_target_right

  s_left_bank_target_left:
    switch: s_left_bank_target_left
  s_left_bank_target_middle:
    switch: s_left_bank_target_middle
  s_left_bank_target_right:
    switch: s_left_bank_target_right

# -------------------------------
# DROP TARGET BANKS
# -------------------------------
drop_target_banks:
  right_bank:
    drop_targets:
      - s_right_bank_target_left
      - s_right_bank_target_middle
      - s_right_bank_target_right
    reset_coil: c_drop_target_right
    reset_on_complete: true
    reset_events: ball_starting

  left_bank:
    drop_targets:
      - s_left_bank_target_left
      - s_left_bank_target_middle
      - s_left_bank_target_right
    reset_coil: c_drop_target_left
    reset_on_complete: true
    reset_events: ball_starting, mode_escape_graveyard_started