#config_version=6

switches:
  #Cabinet Switches
  s_start_button:
    number: 06
    tags: start
  s_tilt:
    number: 07
    tags: tilt
  s_coin_right:
    number: 09
    tags: coin_right
  s_credit_button:
    number: 10
    tags: credit_button
  s_slam_tilt:
    number: 16
    tags: slam_tilt

  #Playfield Switches:
  s_right_rollover:
    number: 01
    tags: right_rollover
  s_middle_skill_lane:
    number: 02
    tags: middle_skill_lane
  s_left_rollover:
    number: 03
    tags: left_rollover
  s_right_skill_lane:
    number: 04
    tags: right_skill_lane 
  s_left_bank_target_left:
    number: 05
    tags: left_bank_target_left
  s_trough:
    number: 08
    tags: trough 
  s_stand_up:
    number: 12
    tags: stand_up
  s_left_bank_target_right:
    number: 13
    tags: left_bank_target_right
  s_right_bank_target_right:
    number: 14
    tags: right_bank_target_right
  s_spinner:
    number: 15
    debounce: quick
    type: NC
    tags: spinner
  s_middle_rollover:
    number: 17
    tags: middle_rollover
  s_left_lower_bumper:
    number: 18
    tags: left_lower_bumper
  s_left_upper_bumper:
    number: 19
    tags: left_upper_bumper
  s_left_skill_lane:
    number: 20
    tags: left_skill_lane
  s_left_bank_target_middle:
    number: 21
    tags: left_bank_target_middle
  s_right_bank_target_middle:
    number: 22
    tags: right_bank_target_middle 
  s_rollover_upper:
    number: 23
    tags: rollover_upper
  s_saucer:
    number: 24
    tags: saucer
  s_right_outlane:
    number: 25
    tags: right_outlane
  s_left_outlane:
    number: 27
    tags: left_outlane
  s_right_bank_target_left:
    number: 30
    tags: right_bank_target_left
  s_left_inlane:
    number: 32
    tags: left_inlane, playfield_active
  s_middle_pop_bumper:
    number: 33
    tags: middle_pop_bumper
  s_right_pop_bumper:
    number: 34
    tags: right_pop_bumper
  s_left_pop_bumper:
    number: 35
    tags: left_pop_bumper
  s_right_sling:
    number: 38
    tags: right_sling
  s_left_sling:
    number: 39
    tags: left_sling
  s_right_inlane:
    number: 40
    tags: right_inlane, playfield_active
